export default {
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME_SCREEN: 'HOME_SCREEN',
  QUESTION_SCREEN: 'QUESTION_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',

  AUTH_CONTAINER: 'AUTH_CONTAINER',
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  FORGET_PASS_SCREEN: 'FORGET_PASS_SCREEN',
  RE_SIGN_IN_SCREEN: 'RE_SIGN_IN_SCREEN',

  COMMON_CONTAINER: 'COMMON_CONTAINER',
  SETTING_PROFILE_SCREEN: 'SETTING_PROFILE_SCREEN',
};
